name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Vib
      run: |
        wget https://github.com/Vanilla-OS/Vib/releases/download/v0.2.7/vib
        chmod +x vib
        ./vib build recipe.yml

    - name: Build the Docker image
      run: docker image build -f Containerfile --tag vanillaos/desktop:${{ github.ref_name }} .

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: vanillaos/desktop
        tags: ${{ github.ref_name }}
        registry: ${{ secrets.NEXUS_REGISTRY }}
        username: ${{ secrets.NEXUS_USER }}
        password: ${{ secrets.NEXUS_PSW }}
        tls-verify: false
